import localFont from "next/font/local";
import "./globals.css";
import CommonLayout from "./components/common-layout";
import { SemInfoProvider } from "./components/context";
import Dialogbox from "./components/dialogbox";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "NoteRIT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <title>NoteRIT</title>
          <meta name="description" content="AI Branch portal" />
          <link rel="shortcut icon" href="/images/applogo32.png" type="image/png" />
          <meta property="og:image" content="/images/applogo32.png"/>
          <meta property="og:url" content="https://noterit.vercel.app" />
          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#000000" />
          <link rel="apple-touch-icon" href="/images/applogo192.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-slate-950 `}
      >
        <SemInfoProvider>
          <CommonLayout
            children={children}
          />
          <Dialogbox/>
        </SemInfoProvider>
        
      </body>
    </html>
  );
}
